version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env
    depends_on:
      - db
  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: cargo_booking
    ports:
      - '5432:5432'
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend